name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            echo "Updating backend..."

            cd /root/bankguard/backend

            git pull origin main

            npm install

            pm2 restart bankguard-api --update-env

            pm2 save